msg = input('Digite alguma coisa:')
print(type(msg))
print(msg.isalnum())
print(msg.isalpha())
print(msg.isascii())
print(msg.isdigit())
print(msg.islower())
print(msg.isdecimal())
print(msg.isidentifier())
print(msg.isupper())
